M48
; DRILL file {KiCad 6.0.4-6f826c9f35~116~ubuntu20.04.1} date Tue Jun 14 10:26:02 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-06-14T10:26:02+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.4-6f826c9f35~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X140.015Y-90.354
X140.015Y-110.674
T0
M30
